#pragma once
//#define EC "\e"
#define EC "\033"
#define ANSI_RESET              "\x1b[0m"

#define ANSI_BLACK              EC "[30m"
#define ANSI_RED                EC "[31m"
#define ANSI_GREEN              EC "[32m"
#define ANSI_YELLOW             EC "[33m"
#define ANSI_BLUE               EC "[34m"
#define ANSI_MAGENTA            EC "[35m"
#define ANSI_CYAN               EC "[36m"
#define ANSI_WHITE              EC "[37m"

#define ANSI_BRIGHT_BLACK       EC "[1;30m"
#define ANSI_BRIGHT_RED         EC "[1;31m"
#define ANSI_BRIGHT_GREEN       EC "[1;32m"
#define ANSI_BRIGHT_YELLOW      EC "[1;33m"
#define ANSI_BRIGHT_BLUE        EC "[1;34m"
#define ANSI_BRIGHT_MAGENTA     EC "[1;35m"
#define ANSI_BRIGHT_CYAN        EC "[1;36m"
#define ANSI_BRIGHT_WHITE       EC "[1;37m"

#define ANSI_BACKGROUND_BLACK   EC "[40m"
#define ANSI_BACKGROUND_RED     EC "[41m"
#define ANSI_BACKGROUND_GREEN   EC "[42m"
#define ANSI_BACKGROUND_YELLOW  EC "[43m"
#define ANSI_BACKGROUND_BLUE    EC "[44m"
#define ANSI_BACKGROUND_MAGENTA EC "[45m"
#define ANSI_BACKGROUND_CYAN    EC "[46m"
#define ANSI_BACKGROUND_WHITE   EC "[47m"

#define ANSI_UNDERLINE_BLACK    EC "[4;30m"
#define ANSI_UNDERLINE_RED      EC "[4;31m"
#define ANSI_UNDERLINE_GREEN    EC "[4;32m"
#define ANSI_UNDERLINE_YELLOW   EC "[4;33m"
#define ANSI_UNDERLINE_BLUE     EC "[4;34m"
#define ANSI_UNDERLINE_MAGENTA  EC "[4;35m"
#define ANSI_UNDERLINE_CYAN     EC "[4;36m"
#define ANSI_UNDERLINE_WHITE    EC "[4;37m"
