#pragma once

#define START_PAD TOUCH_PAD_NUM0
int START_T = 1460;

#define SELECT_PAD TOUCH_PAD_NUM2
int SELECT_T = 0;

#define X_PAD TOUCH_PAD_NUM3
int X_T = 595;

#define DOWN_PAD TOUCH_PAD_NUM4
int DOWN_T = 110;

#define LEFT_PAD TOUCH_PAD_NUM4
int LEFT_T = 110;

#define RIGHT_PAD TOUCH_PAD_NUM5
int RIGHT_T = 200;

#define UP_PAD TOUCH_PAD_NUM6
int UP_T = 234;

#define O_PAD TOUCH_PAD_NUM7
int O_T = 295;

#define TUNING_AMOUNT 3
